"""Validate language messages and generate the synchronous static language bundle."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def build_catalog(folder: Path) -> dict:
    registry = json.loads((folder / "index.json").read_text(encoding="utf-8"))
    english = json.loads((folder / "en.json").read_text(encoding="utf-8"))
    catalog = {}
    for code, meta in registry.items():
        if not re.fullmatch(r"[a-z]{2}(?:-[A-Z]{2})?", code) or meta["dir"] not in ("ltr", "rtl"):
            raise ValueError(f"Invalid language metadata: {code}")
        messages = json.loads((folder / f"{code}.json").read_text(encoding="utf-8"))
        preview = meta.get("status") == "preview"
        if messages.keys() - english.keys() or (not preview and messages.keys() != english.keys()):
            raise ValueError(f"Missing or unknown translation keys in {code}: {sorted(english.keys() - messages.keys())}")
        for key, text in messages.items():
            if not isinstance(text, str) or not text.strip():
                raise ValueError(f"Empty translation: {code}.{key}")
            parameters = set(re.findall(r"\{(\w+)\}", text))
            expected = set(re.findall(r"\{(\w+)\}", english[key]))
            if parameters != expected:
                raise ValueError(f"Translation parameters differ: {code}.{key}")
        required = {key for key in english if key.startswith(("template.", "action.", "count."))}
        if required - messages.keys():
            raise ValueError(f"Missing dynamic messages in {code}")
        catalog[code] = {**meta, "messages": messages, "translatedMessages": len(messages), "totalMessages": len(english)}
    return catalog


def run(folder: Path = ROOT / "config/locales", docs_dir: Path = ROOT / "docs", *, check: bool = False) -> None:
    catalog = build_catalog(folder)
    target = docs_dir / "assets/language-catalog.js"
    script = "// Generated by python -m src.ftg.build_language_catalog. Edit config/locales/.\nwindow.TALENT_GEO_LANGUAGE_CATALOG = " + json.dumps(catalog, ensure_ascii=False, separators=(",", ":")) + ";\n"
    if check:
        if target.read_text(encoding="utf-8") != script:
            raise ValueError("Language bundle is stale; run python -m src.ftg.build_language_catalog")
    else:
        target.write_text(script, encoding="utf-8")
    for page in [docs_dir / "index.html", *sorted(docs_dir.glob("*/index.html"))]:
        html = page.read_text(encoding="utf-8")
        prefix = "./" if page.parent == docs_dir else "../"
        updated = html
        if "assets/language-catalog.js" not in updated:
            updated = updated.replace(f'<script src="{prefix}assets/site-language.js">', f'<script src="{prefix}assets/language-catalog.js"></script><script src="{prefix}assets/site-language.js">')
        if check and updated != html:
            raise ValueError(f"Language assets are stale: {page}")
        if not check and updated != html:
            page.write_text(updated, encoding="utf-8")
    print(f"Validated {len(catalog)} languages against {len(catalog['en']['messages'])} source messages")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    run(check=args.check)


if __name__ == "__main__":
    main()
