"""Generate navigation and renderer settings from edition configuration and snapshots."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]


def validate_dashboard(payload: dict[str, Any], edition: dict[str, Any]) -> None:
    records = payload["records"]
    summary = payload["summary"]
    identities: dict[str, dict[str, Any]] = {}
    contributions = set()
    for row in records:
        identifier = row.get("id")
        if not identifier or not row.get("name"):
            raise ValueError("Every participant requires an ID and name")
        key = (identifier, row.get("team"), row.get("year"))
        if key in contributions or (identifier in identities and edition["id"] != "football"):
            raise ValueError(f"Duplicate participant contribution: {identifier}")
        contributions.add(key)
        previous = identities.get(identifier)
        if previous and any(previous.get(field) != row.get(field) for field in ("mapped", "lat", "lon", "place", "country")):
            raise ValueError(f"Conflicting geography for {identifier}")
        identities[identifier] = row
        if row.get("mapped"):
            lat, lon = row.get("lat"), row.get("lon")
            if not isinstance(lat, (int, float)) or not isinstance(lon, (int, float)) or not (-90 <= lat <= 90 and -180 <= lon <= 180):
                raise ValueError(f"Invalid coordinates for {identifier}")
        workload = row.get(edition["workloadField"], 0)
        if not isinstance(workload, (int, float)) or not 0 <= workload < float("inf"):
            raise ValueError(f"Invalid workload for {identifier}")
    if summary["players"] != len(identities):
        raise ValueError("Participant summary does not reconcile")
    mapped = sum(bool(row.get("mapped")) for row in identities.values())
    if summary["mapped_players"] != mapped or summary["unresolved_players"] != len(identities) - mapped:
        raise ValueError("Mapping summary does not reconcile")
    workload_field = edition["workloadField"]
    workload = sum(row.get(workload_field, 0) for row in records)
    if abs(workload - summary[workload_field]) > max(1e-6, abs(workload) * 1e-9):
        raise ValueError("Workload summary does not reconcile")


def build_catalog(config: dict[str, Any], docs_dir: Path) -> list[dict[str, Any]]:
    if config.get("schemaVersion") != 1:
        raise ValueError("Unsupported edition configuration version")
    output = []
    seen = set()
    for entry in config["editions"]:
        if entry["id"] in seen:
            raise ValueError(f"Duplicate edition: {entry['id']}")
        seen.add(entry["id"])
        relative = Path(entry["path"])
        if relative.is_absolute() or ".." in relative.parts:
            raise ValueError("Edition paths must stay inside docs")
        payload = json.loads((docs_dir / relative / "data/dashboard.json").read_text(encoding="utf-8"))
        validate_dashboard(payload, entry)
        meta, summary = payload["meta"], payload["summary"]
        people = {row["id"]: row for row in payload["records"]}
        birthplaces = sum(bool(row.get("mapped")) and row.get("locationType", "birthplace") in (None, "birthplace") for row in people.values())
        years = meta.get("years", [meta.get("year")])
        season = meta.get("season") or f"{years[0] - 1}–{str(years[0])[-2:]}"
        output.append({
            **entry, "season": season, "scope": meta["scope"],
            "year": meta.get("year"), "years": meta.get("years", [meta.get("year")]),
            "groups": meta.get("conferences", meta.get("leagues", [])),
            "participants": summary["players"], "mappedParticipants": summary["mapped_players"],
            "birthplaceParticipants": birthplaces,
            "coverage": round(birthplaces / summary["players"] * 100, 1) if summary["players"] else 0,
            "mappedCoverage": summary["player_coverage_pct"],
        })
    return output


def render_script(catalog: list[dict[str, Any]]) -> str:
    return "// Generated by python -m src.ftg.build_edition_catalog. Edit config/editions.json.\nwindow.TALENT_GEO_CATALOG = " + json.dumps(catalog, ensure_ascii=False, separators=(",", ":")) + ";\n"


def run(config_path: Path = ROOT / "config/editions.json", docs_dir: Path = ROOT / "docs", *, check: bool = False) -> None:
    catalog = build_catalog(json.loads(config_path.read_text(encoding="utf-8")), docs_dir)
    target = docs_dir / "assets/edition-catalog.js"
    script = render_script(catalog)
    if check:
        if target.read_text(encoding="utf-8") != script:
            raise ValueError("Edition catalog is stale; run python -m src.ftg.build_edition_catalog")
    else:
        target.write_text(script, encoding="utf-8")
    for page in [docs_dir / "index.html", *sorted(docs_dir.glob("*/index.html"))]:
        html = page.read_text(encoding="utf-8")
        prefix = "./" if page.parent == docs_dir else "../"
        updated = html
        if "assets/edition-catalog.js" not in updated:
            updated = updated.replace(f'<script src="{prefix}assets/sport-navigation.js">', f'<script src="{prefix}assets/edition-catalog.js"></script><script src="{prefix}assets/sport-navigation.js">')
        entry = next((item for item in catalog if docs_dir / item["path"] / "index.html" == page), None)
        if entry and entry.get("renderer"):
            renderer = "{" + ",".join(key + ":" + json.dumps(value, ensure_ascii=False, separators=(",", ":")) for key, value in entry["renderer"].items()) + "}"
            if "window.TALENT_GEO_EDITION" in updated:
                updated = re.sub(r"window.TALENT_GEO_EDITION\s*=\s*\{.*?\};", lambda _: "window.TALENT_GEO_EDITION=" + renderer + ";", updated, flags=re.S)
            else:
                updated = updated.replace(f'<script src="{prefix}assets/league-app.js">', f'<script>window.TALENT_GEO_EDITION={renderer};</script><script src="{prefix}assets/league-app.js">')
        if check and updated != html:
            raise ValueError(f"Edition assets are stale: {page}")
        if not check and updated != html:
            page.write_text(updated, encoding="utf-8")
    print(f"Validated {len(catalog)} editions")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=ROOT / "config/editions.json")
    parser.add_argument("--docs-dir", type=Path, default=ROOT / "docs")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    run(args.config, args.docs_dir, check=args.check)


if __name__ == "__main__":
    main()
